import json
from datetime import datetime


def export_chat_pdf(file_name: str, messages: list[dict], summary: dict = None) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
    from io import BytesIO

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2*cm
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "Title", parent=styles["Title"],
        fontSize=20, textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=6
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"],
        fontSize=10, textColor=colors.HexColor("#6b7280"),
        spaceAfter=20
    )
    question_style = ParagraphStyle(
        "Question", parent=styles["Normal"],
        fontSize=11, textColor=colors.HexColor("#1d4ed8"),
        fontName="Helvetica-Bold",
        spaceBefore=14, spaceAfter=6,
        leftIndent=0
    )
    answer_style = ParagraphStyle(
        "Answer", parent=styles["Normal"],
        fontSize=10, textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=8, leading=16,
        leftIndent=10
    )
    source_style = ParagraphStyle(
        "Source", parent=styles["Normal"],
        fontSize=8, textColor=colors.HexColor("#9ca3af"),
        leftIndent=10, spaceAfter=4
    )
    section_style = ParagraphStyle(
        "Section", parent=styles["Normal"],
        fontSize=12, textColor=colors.HexColor("#1a1a2e"),
        fontName="Helvetica-Bold",
        spaceBefore=16, spaceAfter=8
    )

    story = []

    # Header
    story.append(Paragraph("DocIntel", title_style))
    story.append(Paragraph(f"Chat Export — {file_name}", subtitle_style))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y %H:%M')}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e8eaed")))
    story.append(Spacer(1, 12))

    # Summary section
    if summary and summary.get("details"):
        details = summary["details"]
        story.append(Paragraph("Document Summary", section_style))

        if details.get("overview"):
            story.append(Paragraph(details["overview"], answer_style))

        if details.get("key_topics"):
            topics = ", ".join(details["key_topics"])
            story.append(Paragraph(f"<b>Key Topics:</b> {topics}", answer_style))

        if details.get("document_type"):
            story.append(Paragraph(f"<b>Document Type:</b> {details['document_type']}", answer_style))

        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e8eaed")))
        story.append(Spacer(1, 12))

    # Chat history
    story.append(Paragraph("Conversation", section_style))

    q_count = 1
    for msg in messages:
        if msg["role"] == "user":
            story.append(Paragraph(f"Q{q_count}: {msg['content']}", question_style))
            q_count += 1
        elif msg["role"] == "assistant":
            # Clean content for PDF
            content = msg["content"].replace("\n", "<br/>")
            story.append(Paragraph(content, answer_style))

            # Sources
            sources = msg.get("sources", [])
            if sources:
                for s in sources[:3]:  # show max 3 sources
                    file_info = f" · {s.get('file', '')}" if s.get("file") else ""
                    story.append(Paragraph(
                        f"[Source: Page {s.get('page', '?')}{file_info}] {s.get('preview', '')[:100]}...",
                        source_style
                    ))

            story.append(Spacer(1, 6))

    # Footer
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e8eaed")))
    story.append(Paragraph("Generated by DocIntel — AI Document Intelligence", subtitle_style))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()


def export_chat_docx(file_name: str, messages: list[dict], summary: dict = None) -> bytes:
    from docx import Document
    from docx.shared import Pt, RGBColor, Cm
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from io import BytesIO

    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin = Cm(2)
        section.bottom_margin = Cm(2)
        section.left_margin = Cm(2.5)
        section.right_margin = Cm(2.5)

    # Title
    title = doc.add_heading("DocIntel — Chat Export", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.LEFT
    title.runs[0].font.color.rgb = RGBColor(0x1a, 0x1a, 0x2e)

    # Subtitle
    sub = doc.add_paragraph(f"Document: {file_name}")
    sub.runs[0].font.size = Pt(10)
    sub.runs[0].font.color.rgb = RGBColor(0x6b, 0x72, 0x80)

    date_p = doc.add_paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y %H:%M')}")
    date_p.runs[0].font.size = Pt(10)
    date_p.runs[0].font.color.rgb = RGBColor(0x6b, 0x72, 0x80)

    doc.add_paragraph()

    # Summary
    if summary and summary.get("details"):
        details = summary["details"]
        doc.add_heading("Document Summary", level=1)

        if details.get("overview"):
            doc.add_paragraph(details["overview"])

        if details.get("key_topics"):
            p = doc.add_paragraph()
            run = p.add_run("Key Topics: ")
            run.bold = True
            p.add_run(", ".join(details["key_topics"]))

        if details.get("document_type"):
            p = doc.add_paragraph()
            run = p.add_run("Document Type: ")
            run.bold = True
            p.add_run(details["document_type"])

        doc.add_paragraph()

    # Chat
    doc.add_heading("Conversation", level=1)

    q_count = 1
    for msg in messages:
        if msg["role"] == "user":
            p = doc.add_paragraph()
            run = p.add_run(f"Q{q_count}: {msg['content']}")
            run.bold = True
            run.font.color.rgb = RGBColor(0x1d, 0x4e, 0xd8)
            run.font.size = Pt(11)
            q_count += 1

        elif msg["role"] == "assistant":
            p = doc.add_paragraph(msg["content"])
            p.runs[0].font.size = Pt(10)

            sources = msg.get("sources", [])
            if sources:
                for s in sources[:3]:
                    file_info = f" · {s.get('file', '')}" if s.get("file") else ""
                    sp = doc.add_paragraph(
                        f"[Source: Page {s.get('page', '?')}{file_info}] {s.get('preview', '')[:100]}..."
                    )
                    sp.runs[0].font.size = Pt(8)
                    sp.runs[0].font.color.rgb = RGBColor(0x9c, 0xa3, 0xaf)

            doc.add_paragraph()

    # Footer
    footer_p = doc.add_paragraph("Generated by DocIntel — AI Document Intelligence")
    footer_p.runs[0].font.size = Pt(8)
    footer_p.runs[0].font.color.rgb = RGBColor(0x9c, 0xa3, 0xaf)

    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.read()